export const cet4Words = [
  { word: 'abandon', phonetic: '/əˈbændən/', pos: 'v.', meaning: '放弃；抛弃', level: 2, tag: '高频', family: ['abandoned', 'abandonment'], example: 'Students should not abandon a goal just because progress is slow.' },
  { word: 'ability', phonetic: '/əˈbɪləti/', pos: 'n.', meaning: '能力；才能', level: 1, tag: '基础', family: ['able', 'unable'], example: 'Reading every day improves your ability to understand long passages.' },
  { word: 'absorb', phonetic: '/əbˈzɔːrb/', pos: 'v.', meaning: '吸收；理解；使全神贯注', level: 3, tag: '阅读', family: ['absorbed', 'absorption'], example: 'The material can absorb water quickly.' },
  { word: 'academic', phonetic: '/ˌækəˈdemɪk/', pos: 'adj.', meaning: '学术的；学院的', level: 2, tag: '校园', family: ['academy'], example: 'Academic writing requires clear evidence and careful reasoning.' },
  { word: 'access', phonetic: '/ˈækses/', pos: 'n./v.', meaning: '通道；机会；访问', level: 2, tag: '科技', family: ['accessible'], example: 'Students need access to reliable learning resources.' },
  { word: 'accomplish', phonetic: '/əˈkɑːmplɪʃ/', pos: 'v.', meaning: '完成；实现', level: 3, tag: '写作', family: ['accomplishment'], example: 'A weekly plan helps you accomplish more with less stress.' },
  { word: 'accurate', phonetic: '/ˈækjərət/', pos: 'adj.', meaning: '准确的；精确的', level: 2, tag: '写作', family: ['accuracy'], example: 'Accurate notes make revision much easier.' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', pos: 'v.', meaning: '实现；达到', level: 1, tag: '高频', family: ['achievement'], example: 'You can achieve steady progress by reviewing words regularly.' },
  { word: 'adapt', phonetic: '/əˈdæpt/', pos: 'v.', meaning: '适应；改编', level: 3, tag: '阅读', family: ['adaptation'], example: 'Freshmen need time to adapt to college life.' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', pos: 'adj.', meaning: '足够的；适当的', level: 4, tag: '阅读', family: ['adequately'], example: 'Adequate preparation reduces exam anxiety.' },
  { word: 'affect', phonetic: '/əˈfekt/', pos: 'v.', meaning: '影响', level: 2, tag: '易混', family: ['effect'], example: 'Sleep can affect memory and concentration.' },
  { word: 'agriculture', phonetic: '/ˈæɡrɪkʌltʃər/', pos: 'n.', meaning: '农业', level: 4, tag: '社会', family: ['agricultural'], example: 'Technology is changing modern agriculture.' },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', pos: 'n./adj.', meaning: '替代选择；可替代的', level: 3, tag: '写作', family: ['alternatively'], example: 'Online courses are an alternative to traditional classes.' },
  { word: 'analyze', phonetic: '/ˈænəlaɪz/', pos: 'v.', meaning: '分析', level: 2, tag: '学术', family: ['analysis', 'analytical'], example: 'The report analyzes why students forget new words.' },
  { word: 'annual', phonetic: '/ˈænjuəl/', pos: 'adj.', meaning: '每年的；年度的', level: 2, tag: '商务', family: ['annually'], example: 'The annual survey shows changes in reading habits.' },
  { word: 'approach', phonetic: '/əˈproʊtʃ/', pos: 'n./v.', meaning: '方法；接近；处理', level: 2, tag: '高频', family: ['approachable'], example: 'A better approach is to learn words in context.' },
  { word: 'appropriate', phonetic: '/əˈproʊpriət/', pos: 'adj.', meaning: '合适的；恰当的', level: 3, tag: '写作', family: ['appropriately'], example: 'Choose an appropriate word for each sentence.' },
  { word: 'benefit', phonetic: '/ˈbenɪfɪt/', pos: 'n./v.', meaning: '益处；受益', level: 1, tag: '写作', family: ['beneficial'], example: 'Regular exercise benefits both body and mind.' },
  { word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', pos: 'n./v.', meaning: '挑战；质疑', level: 1, tag: '高频', family: ['challenging'], example: 'Remembering similar words is a common challenge.' },
  { word: 'circumstance', phonetic: '/ˈsɜːrkəmstæns/', pos: 'n.', meaning: '情况；环境', level: 4, tag: '阅读', family: ['circumstantial'], example: 'Under no circumstances should you ignore safety rules.' },
  { word: 'community', phonetic: '/kəˈmjuːnəti/', pos: 'n.', meaning: '社区；群体', level: 1, tag: '社会', family: ['communal'], example: 'Volunteers make the community more welcoming.' },
  { word: 'compare', phonetic: '/kəmˈper/', pos: 'v.', meaning: '比较；相比', level: 2, tag: '写作', family: ['comparison'], example: 'Compare the two methods before making a decision.' },
  { word: 'concentrate', phonetic: '/ˈkɑːnsntreɪt/', pos: 'v.', meaning: '集中注意力；浓缩', level: 3, tag: '学习', family: ['concentration'], example: 'It is hard to concentrate when the room is noisy.' },
  { word: 'consequence', phonetic: '/ˈkɑːnsəkwens/', pos: 'n.', meaning: '结果；后果', level: 4, tag: '写作', family: ['consequently'], example: 'Every choice has a consequence.' },
  { word: 'consume', phonetic: '/kənˈsuːm/', pos: 'v.', meaning: '消费；消耗', level: 3, tag: '社会', family: ['consumer', 'consumption'], example: 'Short videos can consume too much study time.' },
  { word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', pos: 'v.', meaning: '贡献；促成', level: 3, tag: '写作', family: ['contribution'], example: 'Vocabulary contributes to reading speed.' },
  { word: 'decline', phonetic: '/dɪˈklaɪn/', pos: 'n./v.', meaning: '下降；拒绝', level: 3, tag: '数据', family: ['declining'], example: 'The chart shows a decline in paper dictionary use.' },
  { word: 'demonstrate', phonetic: '/ˈdemənstreɪt/', pos: 'v.', meaning: '证明；展示', level: 4, tag: '学术', family: ['demonstration'], example: 'Examples demonstrate how a word is used.' },
  { word: 'efficient', phonetic: '/ɪˈfɪʃnt/', pos: 'adj.', meaning: '高效的', level: 2, tag: '写作', family: ['efficiency'], example: 'An efficient review system saves time.' },
  { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', pos: 'n.', meaning: '环境', level: 1, tag: '社会', family: ['environmental'], example: 'A quiet environment helps students learn.' },
  { word: 'essential', phonetic: '/ɪˈsenʃl/', pos: 'adj.', meaning: '必要的；本质的', level: 2, tag: '高频', family: ['essentially'], example: 'Review is essential for long-term memory.' },
  { word: 'evidence', phonetic: '/ˈevɪdəns/', pos: 'n.', meaning: '证据', level: 3, tag: '写作', family: ['evident'], example: 'The essay needs evidence to support its opinion.' },
  { word: 'expand', phonetic: '/ɪkˈspænd/', pos: 'v.', meaning: '扩大；扩展', level: 2, tag: '高频', family: ['expansion'], example: 'Reading newspapers can expand your vocabulary.' },
  { word: 'frequent', phonetic: '/ˈfriːkwənt/', pos: 'adj.', meaning: '频繁的', level: 2, tag: '高频', family: ['frequently'], example: 'Frequent review prevents forgetting.' },
  { word: 'identify', phonetic: '/aɪˈdentɪfaɪ/', pos: 'v.', meaning: '识别；确认', level: 3, tag: '学术', family: ['identity', 'identification'], example: 'The system identifies your weak words automatically.' },
  { word: 'impact', phonetic: '/ˈɪmpækt/', pos: 'n./v.', meaning: '影响；冲击', level: 2, tag: '写作', family: ['impactful'], example: 'Sleep has a strong impact on learning.' },
  { word: 'maintain', phonetic: '/meɪnˈteɪn/', pos: 'v.', meaning: '保持；维护；主张', level: 3, tag: '高频', family: ['maintenance'], example: 'Maintain a stable review habit before the exam.' },
  { word: 'obvious', phonetic: '/ˈɑːbviəs/', pos: 'adj.', meaning: '明显的', level: 1, tag: '基础', family: ['obviously'], example: 'It is obvious that practice improves confidence.' },
  { word: 'participate', phonetic: '/pɑːrˈtɪsɪpeɪt/', pos: 'v.', meaning: '参加；参与', level: 3, tag: '校园', family: ['participation'], example: 'Students are encouraged to participate in class discussions.' },
  { word: 'predict', phonetic: '/prɪˈdɪkt/', pos: 'v.', meaning: '预测', level: 3, tag: '数据', family: ['prediction'], example: 'Past performance cannot always predict future results.' },
  { word: 'recommend', phonetic: '/ˌrekəˈmend/', pos: 'v.', meaning: '推荐；建议', level: 2, tag: '高频', family: ['recommendation'], example: 'The teacher recommended a new reading list.' },
  { word: 'significant', phonetic: '/sɪɡˈnɪfɪkənt/', pos: 'adj.', meaning: '重要的；显著的', level: 4, tag: '写作', family: ['significance'], example: 'Small daily habits can lead to significant progress.' },
  { word: 'strategy', phonetic: '/ˈstrætədʒi/', pos: 'n.', meaning: '策略', level: 3, tag: '学习', family: ['strategic'], example: 'A good strategy balances new words and review.' },
  { word: 'sufficient', phonetic: '/səˈfɪʃnt/', pos: 'adj.', meaning: '足够的', level: 4, tag: '写作', family: ['sufficiently'], example: 'Sufficient sleep is important before an exam.' },
  { word: 'transfer', phonetic: '/trænsˈfɜːr/', pos: 'v./n.', meaning: '转移；调动；换乘', level: 3, tag: '校园', family: ['transferable'], example: 'You can transfer this method to other subjects.' }
];
